# .github/workflows/deploy.yml
name: Deploy Camcookie AI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Use a self-hosted runner or one you keep online for hosting
    runs-on: [self-hosted, linux]

    # Inject your SECRET_KEY from GitHub Secrets
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database
        run: |
          python - <<EOF
          from app import init_db
          init_db()
          EOF

      - name: Run Camcookie AI
        # Run uvicorn in the background (adjust host/port as needed)
        run: |
          nohup uvicorn app:app --host 0.0.0.0 --port 8000 &> uvicorn.log &